"""Generate docs/MAST-COVERAGE.md from the traces in tests/mast/.

The coverage claim in `docs/MAST-GATES.md` used to be a sentence someone typed:
'14 of 14 modes mapped'. Sentences do not notice when a gate is renamed or a
trace deleted. This derives the table from the traces instead, and
`--check` fails when the committed table no longer matches them, so the number
in the docs cannot outlive the tests that justify it.

Usage:
    python tools/gen_coverage.py            # rewrite docs/MAST-COVERAGE.md
    python tools/gen_coverage.py --check    # exit 1 if it is stale

`--check` compares parsed table rows, not bytes: prose around the table is
editable by hand, the table is not.
"""

from __future__ import annotations

import argparse
import json
import sys
from collections import defaultdict
from pathlib import Path

HEADER = "| Mode | Gate | blocked | cleared |"
SEPARATOR = "|---|---|---|---|"
BANNER = "<!-- Generated by tools/gen_coverage.py. Do not edit the table by hand. -->"
Row = tuple[str, str, int, int]


def load_traces(repo: Path) -> list[dict[str, object]]:
    traces: list[dict[str, object]] = []
    for path in sorted((repo / "tests" / "mast").glob("*.jsonl")):
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.strip():
                traces.append(json.loads(line))
    return traces


def rows_from_traces(traces: list[dict[str, object]]) -> list[Row]:
    counts: dict[tuple[str, str], dict[str, int]] = defaultdict(
        lambda: {"blocking": 0, "clear": 0}
    )
    for trace in traces:
        key = (str(trace["mode"]), str(trace["gate"]))
        counts[key][str(trace["expect"])] += 1
    return [
        (mode, gate, counts[(mode, gate)]["blocking"], counts[(mode, gate)]["clear"])
        for mode, gate in sorted(counts)
    ]


def rows_from_doc(text: str) -> list[Row]:
    rows: list[Row] = []
    for raw in text.splitlines():
        line = raw.strip()
        if not line.startswith("|") or line in {HEADER, SEPARATOR}:
            continue
        cells = [c.strip() for c in line.strip("|").split("|")]
        if len(cells) != 4 or not cells[2].isdigit() or not cells[3].isdigit():
            continue
        rows.append((cells[0], cells[1].replace("`", ""), int(cells[2]), int(cells[3])))
    return sorted(rows)


def render(rows: list[Row]) -> str:
    modes = {mode for mode, _gate, _b, _c in rows}
    total = sum(blocked + cleared for _m, _g, blocked, cleared in rows)

    lines = [
        BANNER,
        "",
        "# Gate coverage, measured",
        "",
        "Every row below was produced by running the named gate against traces in",
        "[`tests/mast/`](../tests/mast/). `blocked` counts traces the gate must reject;",
        "`cleared` counts traces it must let through. Both columns have to be non-zero:",
        "a gate that rejects everything provides no coverage, and one false positive in",
        "`context_carry` was enough to make that concrete during T06.",
        "",
        "For what each gate does and why it sits where it does, see",
        "[MAST-GATES.md](MAST-GATES.md). This file only answers whether the mapping",
        "there is enforced.",
        "",
        HEADER,
        SEPARATOR,
    ]
    lines += [
        f"| {mode} | `{gate}` | {blocked} | {cleared} |"
        for mode, gate, blocked, cleared in rows
    ]
    lines += [
        "",
        f"{total} trace(s), {len(modes)} failure mode(s), {len(rows)} mode/gate pair(s).",
        "",
        "Regenerate with `python tools/gen_coverage.py`. CI runs `--check`, which",
        "compares the table rows only, so the prose above is safe to edit by hand.",
        "",
    ]
    return "\n".join(lines)


def target(repo: Path) -> Path:
    return repo / "docs" / "MAST-COVERAGE.md"


def stale_rows(repo: Path) -> list[str]:
    """Human-readable differences between the committed table and the traces."""
    expected = rows_from_traces(load_traces(repo))
    path = target(repo)
    if not path.exists():
        return [f"{path} does not exist"]

    found = rows_from_doc(path.read_text(encoding="utf-8"))
    problems = [f"missing row: {row}" for row in expected if row not in found]
    problems += [f"unexpected row: {row}" for row in found if row not in expected]
    return problems


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="do not write; fail if stale")
    args = parser.parse_args(argv)

    repo = Path(__file__).resolve().parent.parent

    if args.check:
        problems = stale_rows(repo)
        for problem in problems:
            print(f"stale: {problem}", file=sys.stderr)
        if problems:
            print("run `python tools/gen_coverage.py` to regenerate", file=sys.stderr)
            return 1
        print("docs/MAST-COVERAGE.md matches tests/mast/")
        return 0

    rows = rows_from_traces(load_traces(repo))
    target(repo).write_text(render(rows), encoding="utf-8")
    print(f"wrote {target(repo).relative_to(repo)}: {len(rows)} mode/gate pair(s)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
